### ISSUE TITLE
please add a LICENSE

### ISSUE THREAD

**Issue by waldenn** [mayfer/open-artifacts#1]
Super interesting idea and execution. Thanks!

**Comment by mayfer** [comment]
done

**Comment by waldenn** [comment]
Thanks. Though this means I cant use it in my own project, and will need to remove the experiment. Great idea though!

**Comment by mayfer** [comment]
nah don't remove it, maybe this license was a silly idea, i can give you a free license for life

**Comment by waldenn** [comment]
Hey, all up to you. Any true opensoure license (4 freedoms), will be fine to me. Maybe something like the the GPL license fits your project to allow opensource projects to use it, but you could still sell a version without the license virality (some commercial license) to companies who want to keep their code private. I think this is a good balance, which is why I use that license in my own project. Looking forward to using your project again, as it holds a promise to allow user to create their own custom applications.
